name: ai_coach
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  equatable: ^2.0.7
  firebase_auth: ^5.5.3
  cloud_functions: ^5.5.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
