// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWnrQcVh7rBL5cGQY72VeZC4Lddoen43s',
    appId: '1:1033870425968:web:0784dcc464a92c00b799b5',
    messagingSenderId: '1033870425968',
    projectId: 'aicoach-65e04',
    authDomain: 'aicoach-65e04.firebaseapp.com',
    storageBucket: 'aicoach-65e04.firebasestorage.app',
    measurementId: 'G-E187GYW39B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpyZ6whmp7yRB_L94SqUHflyQ5cSFHAkk',
    appId: '1:1033870425968:android:1e73f80579ae4fe1b799b5',
    messagingSenderId: '1033870425968',
    projectId: 'aicoach-65e04',
    storageBucket: 'aicoach-65e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIeJjVtXyk5FKZaGfcAtfbLxWg2IBhikw',
    appId: '1:1033870425968:ios:a316259ac06ae320b799b5',
    messagingSenderId: '1033870425968',
    projectId: 'aicoach-65e04',
    storageBucket: 'aicoach-65e04.firebasestorage.app',
    iosBundleId: 'com.example.aiCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIeJjVtXyk5FKZaGfcAtfbLxWg2IBhikw',
    appId: '1:1033870425968:ios:a316259ac06ae320b799b5',
    messagingSenderId: '1033870425968',
    projectId: 'aicoach-65e04',
    storageBucket: 'aicoach-65e04.firebasestorage.app',
    iosBundleId: 'com.example.aiCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWnrQcVh7rBL5cGQY72VeZC4Lddoen43s',
    appId: '1:1033870425968:web:268e5b05759ab793b799b5',
    messagingSenderId: '1033870425968',
    projectId: 'aicoach-65e04',
    authDomain: 'aicoach-65e04.firebaseapp.com',
    storageBucket: 'aicoach-65e04.firebasestorage.app',
    measurementId: 'G-B4QYQJBBV1',
  );
}
